### ISSUE TITLE
CI with Travis and docker

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/docker#10]
@arnavs 

The purpose of this issue is to isolate the CI with travis and docker from the sphinx issues, as you were doing in the dockertest.

See https://docs.travis-ci.com/user/languages/julia/#default-build-and-test-script  for a description of the default build script.  If you leave out a build script in the travis file this is what it does.

So my suspicion is that what you need to get working is:
- Assume that Project.toml is in the folder.  Older methods are unsupported with this workflow
- The travis setup clones the appropriate commit for you, and is available local to where you run the docker
- Make sure that docker runs with access to this local folder.  I would start by just testing that with the usual docker lines of local folder mounting before trying to do anything julia
  - See https://docs.travis-ci.com/user/docker/#using-a-docker-image-from-a-repository-in-a-build 
  - I am not sure if this belongs in the `before_install` or in the `script` sections... you can play with it.
- The default julia build script without docker (i.e. if a script is not given in the file) is
```
using Pkg
Pkg.build()
Pkg.test()
```
- So instead, in the build section I think you just need to do that with docker run.  So instead of what you have in dockertest.jl, maybe something like
  - `docker run ?????? julia -e "using Pkg; Pkg.build(); Pkg.test()"`
  - Where the `????` are the settings to make sure you are mounting the local folder.  Maybe you need to do a `cd` first to go to the local mount?  I don't know docker well enough.
- The docker runs with access to the local travis container, which has the cloned repo typically already done for you.

**Comment by arnavs** [comment]
Done. It looks like the build script on Travis is a bit more complicated (they use the `julia --project=@.` to find the local `Project.toml`), so I use that flag as well. 

It looks like this behaves well in the sense that Travis uses the success/failure exit code from Docker, so I think we can close. 

The main lines of the Dockerfile are:

```
before_install: # still runs after Travis checks out the commit 
  - docker pull julia:latest # for now, eventually will be QELAP+Julia
script: # -w flag sets the container's working directory on startup
  - docker run -it --rm -v "$PWD":/usr/myapp -w /usr/myapp julia julia --project=Project.toml -e "using Pkg; Pkg.build(); Pkg.test()"
```

**Comment by jlperla** [comment]
Perfect.  Looks very maintainable to me.  Did I read it correctly that https://travis-ci.com/arnavs/dockertest.jl  ran in 46 seconds, including the docker pull ???  If so, I can't wait to see how long a test using the QELAP takes.

**Comment by jlperla** [comment]
One other thing, looking at a travis build, it looks like the default julia call is
```
"julia --check-bounds=yes --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; Pkg.test(\"${JL_PKG}\", coverage=true); else using Pkg; Pkg.test(coverage=true); end"" 
```
Simplifying that for our assumption of higher versions,
```
"julia --check-bounds=yes --color=yes -e "using Pkg; Pkg.test(coverage=true); end"" 
```

So that suggests adding in ` --check-bounds=yes --color=yes ` and `coverage=true` might be a good idea.  Not essential though.

**Comment by arnavs** [comment]
Sure, we can put those in there.

**Comment by arnavs** [comment]
Also that’s correct — 46s to clone the repo, download the Docker etc., and then run the tests.

I’ll let you know the times for the heavier images.
