### ISSUE TITLE
Automatic Pushing

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/docker#4]
Even though we just merged #3, the DockerHub image isn’t updated. Would be great if there was a CI-type tool that automatically pushes this repo to that one.

Will look around for some.

**Comment by arnavs** [comment]
https://docs.docker.com/docker-hub/builds/

**Comment by sglyon** [comment]
This is already set up.

See here: https://hub.docker.com/r/quantecon/base/builds/

It shows that the quantecon/base image was updated within the last 9 hours

The queue for docker hub's automated builds is sometimes a bit long, so we often have to wait for a while (more than an hour, but less than a day) to get a new image

**Comment by arnavs** [comment]
Thanks @sglyon, wasn’t aware of the delay.
