### ISSUE TITLE
Image naming discussion

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/docker#7]
@sglyon @mmcky @arnavs @cc7768  For discussion before we get too far down the docker path.

We had a conversation a while back about naming the different permutations, but I can't find it, so lets try it again:
There are a few permutations of the docker required.  On one dimension
1. Julia (no jupyter)
  * based on https://hub.docker.com/_/julia/
2. Jupyter support  (Julia + Python)
  * based on `jupyter/base-notebook` or maybe `jupyter/datascience-notebook`... the problem with the second one is that it may have out of date julia.
3. Jupyter support + Jupinx for QE builds 
  * Based on previous one, with additional Sphinx/Jupinx/etc. for lecture notes builds

On the other dimension (for at least the julia ones) determined by what is precompiled and instantiated.
1. QELP
  * https://github.com/QuantEcon/QuantEconLecturePackages
2. QEALP + Differential Equations ecosystem
  * https://github.com/QuantEcon/QuantEconLectureAllPackages
  * Originally had the diffeq stuff separated, but the image size is not sufficiently different
-----------
Why do we need to have different permutations of these?  Partially because a super-set would be enormous, and (especially when CI or parallel dockers are involved) size is important.

So one thought is the following naming scheme (taking inspiration from https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html style)
* `julia` = julia only + QELP
* `all-julia` =  julia only+ QEALP  + diffeq

* `datascience-notebook` = julia + jupyter + QELP
* `all-datascience-notebook` =  = julia + jupyter + QEALP + diffeq

* `jupinx-notebook` = julia + jupyter + QELP + jupinx
* `all-jupinx-notebook` =  = julia + jupyter + QEALP + diffeq +  jupinx
---------
Now, do we really need all of these to start with?  Not really.  I would say the ones to start with (using the above naming convention) is:
1. `quantecon/julia` - useful for a variety of CI jobs where you don't need much, and we could use for an updated `testing.rst` lecture.
2. `quantecon/all-julia` - Useful for CI jobs with complicated projects.  Like a current paper we are working on!
3. `quantecon/all-datascience-notebook` - I think we should replace the current `base` one with this name.  Not sure we need any of the subset ones like `datascience-notebook` and `all-datascience-notebook` since downloading to a desktop or big jupyter setup isn't a problem.
4. `quantecon/all-jupinx-notebook` is the one we would build up for our CI and build infrastructure for all 3 sets of lecture notes.  I don't think we need diffeq for anything with the lecture notes, at this point.

Edit: simplified to mrege all and diffeq

**Comment by jlperla** [comment]
Sorry, I should add in one other comment:  @sglyon had used a docker build here for a server to host students.  I am not sure we want the docker build for that image to be the same as the one you would run on desktops/build servers/etc. since those sorts of jupyterhub installations have different settings.

If we had to come up with a `quantecon/lectures-hub` or something like that, it might make sense.  That could have all of the stuff in https://github.com/QuantEcon/docker/blob/master/extended/Dockerfile that doesn't make sense outside of a classroom jupyterhub.

**Comment by sglyon** [comment]
Quick "fly by" comment

My first response is that there are so many images and I personally would not want to maintain all of them.

**Comment by arnavs** [comment]
We can consolidate the differential equations image with the QELAP one, since they're pretty similar in size. 

Perhaps we could keep the Jupinx image outside of this repo, so it would just be a 2x2 grid (do you have the big or small package set, and do you have Jupyter or not).

**Comment by jlperla** [comment]
Yeah. The other thing is that all this uses hierarchical images for the he docker, so it is typically only a few extra lines to add in the extra stuff.

Even though we will not now (ever?) fill in the matrix entirely, we want to have a consistent naming convention for the ones we choose.

**Comment by arnavs** [comment]
I was having some trouble with the modular extensions on the Jupyter images. But I'll prioritize sorting that out.

**Comment by jlperla** [comment]
@sglyon @arnavs I updated the descriptions and names.  Keep in mind that there are only 4 images suggested here.  @arnavs Getting the hiearchy to work will be essential... In part because people may want to use these as a base to create their own dependent images where they just precompile and add a few packages.

**Comment by arnavs** [comment]
Closing this as it seems that we're good with the naming scheme. Can re-open if that's not the case.
