### ISSUE TITLE
Sphinx/Jupinx docker

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/docker#8]
@mmcky @arnavs 

After building the basic jupyter, we will want to add in all of the features required for sphinx/jupinx/headless execution.  A few useful links:
- [x] Can look at https://github.com/plaindocs/docker-sphinx to see some stuff for general sphinx, pandoc, etc.
- [x] Add in https://github.com/stevengj/NBInclude.jl to the build so we can try various regression testing approaches.
- [x] `pip install sphinxcontrib-bibtex` of course.
- [x] From https://github.com/econtoolkit/tutorials/blob/master/julia/WSL.md I remember needing to do `sudo apt-get install libxt6 libxrender1 libgl1-mesa-glx libqt5widgets5` in order to get GR to work, but maybe it isn't necessary.

**Comment by jlperla** [comment]
Also consider looking at https://github.com/dldl/sphinx-server if things aren't working.

**Comment by arnavs** [comment]
@jlperla OK, I think this is done. It's 6.47 GB (the `jupyter/datascience-notebook` it runs on is 6.29). 

Just to confirm, this is a notebook with (a) a functioning Jupyter setup, (b) Julia + packages (`NBInclude, InstantiateFromURL`), Linux deps, Jupinx/Sphinx and deps, and extras like `pandoc`. 

You can access it "headless" (i.e., without the Jupyter Lab interface) and compile the notebooks, which I did.

**Comment by arnavs** [comment]
OK, closing this since the size looked to be acceptable/we decided not to do this from a `jupyter/minimal-notebook` or something.
